version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./sentence_transformers:/root/.cache/torch/sentence_transformers